PUPPET-123 Fix broken redirect to stderr

diff --git a/templates/usr/local/sbin/check-mysql-database.sh.erb b/templates/usr/local/sbin/check-mysql-database.sh.erb
--- a/templates/usr/local/sbin/check-mysql-database.sh.erb
+++ b/templates/usr/local/sbin/check-mysql-database.sh.erb
@@ -6,12 +6,12 @@
 # otherwise.
 
 if [ -z "$1" ]; then
-  echo "usage: $0 <database>" 1>2&
+  echo "usage: $0 <database>" 1>&2
   exit 1
 fi
 
 if [ "$EUID" -ne "0" ]; then
-  echo "This script must be run as root." 1>2&
+  echo "This script must be run as root." 1>&2
   exit 2
 fi
 
@@ -23,6 +23,6 @@ ps cax | grep -q mysqld > /dev/null
 if [ $? -eq 0 ]; then
   mysql $MYSQL_CREDENTIALS -NBs -e "$QUERY" | grep -qw 0
 else
-  echo "MySQL server not running - check of database ${DATABASE} aborted." 1>2&
+  echo "MySQL server not running - check of database ${DATABASE} aborted." 1>&2
   exit 3
 fi
